// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:Infrastructure.Database.TechLeagueQueryableDbContext.GetPlayersByClubAsync(Domain.Clubs.ClubId,System.String,System.Int32,System.Int32,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Application.Abstractions.PaginationInfo{Application.Clubs.Players.Get.PlayerByClub}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use the 'StringComparison' method overloads to perform case-insensitive string comparisons", Justification = "<Pending>", Scope = "member", Target = "~M:Infrastructure.Database.TechLeagueQueryableDbContext.GetPlayersByClubAsync(Domain.Clubs.ClubId,System.String,System.Int32,System.Int32,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Application.Abstractions.PaginationInfo{Application.Clubs.Players.Get.PlayerByClub}}")]
[assembly: SuppressMessage("Globalization", "CA1311:Specify a culture or use an invariant version", Justification = "<Pending>", Scope = "member", Target = "~M:Infrastructure.Database.TechLeagueQueryableDbContext.GetPlayersByClubAsync(Domain.Clubs.ClubId,System.String,System.Int32,System.Int32,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Application.Abstractions.PaginationInfo{Application.Clubs.Players.Get.PlayerByClub}}")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:Infrastructure.Database.TechLeagueQueryableDbContext.GetPlayersByClubAsync(Domain.Clubs.ClubId,System.String,System.Int32,System.Int32,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Application.Abstractions.PaginatedResult{Application.Clubs.Players.Get.PlayerByClub}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use the 'StringComparison' method overloads to perform case-insensitive string comparisons", Justification = "<Pending>", Scope = "member", Target = "~M:Infrastructure.Database.TechLeagueQueryableDbContext.GetPlayersByClubAsync(Domain.Clubs.ClubId,System.String,System.Int32,System.Int32,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Application.Abstractions.PaginatedResult{Application.Clubs.Players.Get.PlayerByClub}}")]
[assembly: SuppressMessage("Globalization", "CA1311:Specify a culture or use an invariant version", Justification = "<Pending>", Scope = "member", Target = "~M:Infrastructure.Database.TechLeagueQueryableDbContext.GetPlayersByClubAsync(Domain.Clubs.ClubId,System.String,System.Int32,System.Int32,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Application.Abstractions.PaginatedResult{Application.Clubs.Players.Get.PlayerByClub}}")]
