// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(TechLeagueDbContext))]
    partial class TechLeagueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Application.Clubs.Projections.ClubFinanceStatusProjection", b =>
                {
                    b.Property<Guid>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnualBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CoachContractCount")
                        .HasColumnType("int");

                    b.Property<decimal>("CommittedInCoaches")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommittedInPlayers")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlayerContractCount")
                        .HasColumnType("int");

                    b.HasKey("ClubId");

                    b.ToTable("FinanceStatusProjection");
                });

            modelBuilder.Entity("Domain.Clubs.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnualBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommittedAnualBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThreeLettersName")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ThreeLettersName")
                        .IsUnique();

                    b.ToTable("Clubs", t =>
                        {
                            t.HasCheckConstraint("CK_Min_Budget", "AnualBudget > 999999");
                        });
                });

            modelBuilder.Entity("Domain.Coaches.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.ToTable("Coaches", t =>
                        {
                            t.HasCheckConstraint("CK_Min_Experience", "Experience > 5");
                        });
                });

            modelBuilder.Entity("Domain.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnualSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Duration", "Domain.Contracts.Contract.Duration#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("End")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("datetime2");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Contracts", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NickName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("NickName")
                        .IsUnique()
                        .HasFilter("[NickName] IS NOT NULL");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Domain.Coaches.CoachContract", b =>
                {
                    b.HasBaseType("Domain.Contracts.Contract");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CoachId")
                        .IsUnique()
                        .HasFilter("[CoachId] IS NOT NULL");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.Players.PlayerContract", b =>
                {
                    b.HasBaseType("Domain.Contracts.Contract");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasFilter("[PlayerId] IS NOT NULL");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Application.Clubs.Projections.ClubFinanceStatusProjection", b =>
                {
                    b.HasOne("Domain.Clubs.Club", "Club")
                        .WithOne()
                        .HasForeignKey("Application.Clubs.Projections.ClubFinanceStatusProjection", "ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Domain.Contracts.Contract", b =>
                {
                    b.HasOne("Domain.Clubs.Club", "Club")
                        .WithMany("Contracts")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Domain.Coaches.CoachContract", b =>
                {
                    b.HasOne("Domain.Coaches.Coach", "Coach")
                        .WithOne("CurrentContract")
                        .HasForeignKey("Domain.Coaches.CoachContract", "CoachId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Domain.Players.PlayerContract", b =>
                {
                    b.HasOne("Domain.Players.Player", "Player")
                        .WithOne("CurrentContract")
                        .HasForeignKey("Domain.Players.PlayerContract", "PlayerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Domain.Clubs.Club", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Domain.Coaches.Coach", b =>
                {
                    b.Navigation("CurrentContract");
                });

            modelBuilder.Entity("Domain.Players.Player", b =>
                {
                    b.Navigation("CurrentContract");
                });
#pragma warning restore 612, 618
        }
    }
}
